version: "3.8"

services:
  mysql:
    image: mysql
    container_name: mysql_container
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=library
      - MYSQL_USER=library_user
      - MYSQL_PASSWORD=library_password
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.2-alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build: .
    container_name: api_container
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=library_user
      - DB_PASS=library_password
      - DB_NAME=library
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
  redis_data:
